#include "gl.hh"

const unordered_map<int, string> GL::Shader::Types = {
	{GL_COMPUTE_SHADER, "GL_COMPUTE_SHADER"},
	{GL_VERTEX_SHADER, "GL_VERTEX_SHADER"},
	{GL_TESS_CONTROL_SHADER, "GL_TESS_CONTROL_SHADER"},
	{GL_TESS_EVALUATION_SHADER, "GL_TESS_EVALUATION_SHADER"},
	{GL_GEOMETRY_SHADER, "GL_GEOMETRY_SHADER"},
	{GL_FRAGMENT_SHADER, "GL_FRAGMENT_SHADER"},
};
